version: "3.8" #version docker
services: 
  web:
    build: .
    image: toonhudsha/app:1.1.1
    ports:
      - "4000:4000"
  mongo:
    image: mongo:4.2.8
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=secret
      - MONGO_INITDB_DATABASE=mydb
# docper-compose build    = build image
# docper-compose up       = Foreground process
# docper-compose up -d    = Background process
# docper-compose ps       = List of containers
# docker-compose logs web = View log of web service
# docker-compost down     = Remove all resource (container, network, volumn)
# Hub link: https://hub.docker.com/layers/toonhudsha/app/1.1.1/images/sha256-f998ca80070bdc150f1ed8cc6e842367993162a125de10fdc5ce099d83e04f53?context=repo